version: 2.1

jobs:
  build:
    docker:
      - image: tuxonomics/tx-ubuntu-mkl:0.1

    steps:
      - checkout
      - run: make tests-asan
      - run: make tests-asan/blas

workflows:
  "Run Tests":
    jobs:
      - build
